---

- name: Installing libwebkitgtk for eclipse browser support
  become: true
  apt:
    name: libwebkitgtk-1.0-0
    state: latest
    purge: true
    autoremove: true

- name: Creating {{ eclipse_installer_folder | dirname }} directory if it does not exist
  file:
    path: '{{ eclipse_installer_folder | dirname }}'
    state: directory
    mode: 0755

- name: Downloading Eclipse Installer binaries
  get_url:
    url: '{{ eclipse_installer_download_url }}'
    dest: '{{ eclipse_installer_folder | dirname }}'
    timeout: 60
  register: archive

- name: Remove previous {{ eclipse_installer_folder }} direcory
  file:
    path: '{{ eclipse_installer_folder }}'
    state: absent

- name: Extract Eclipse Installer binaries
  unarchive:
    src: '{{ archive.dest }}'
    dest: '{{ eclipse_installer_folder | dirname }}'

- name: Remove downloaded Eclipse Installer archive
  file:
    path: '{{ archive.dest }}'
    state: absent

- name: Configure Eclipse Installer configuration
  copy:
    src: eclipse/
    dest: '{{ eclipse_installer_folder }}'

- name: Add oomph catalog index redirection to config.ini file
  lineinfile:
    dest: '{{ eclipse_installer_folder }}/configuration/config.ini'
    regexp: ^oomph\.redirection\.index\.redirection
    line: oomph.redirection.index.redirection=index:/->{{ eclipse_installer_catalog_index_url }}

- name: Add custom eclipse project catalog to config.ini file
  lineinfile:
    dest: '{{ eclipse_installer_folder }}/configuration/config.ini'
    regexp: ^oomph\.redirection\.projects\.catalog
    line: oomph.redirection.projects.catalog=index:/redirectable.projects.catalog.setup->{{ eclipse_installer_redirectable_projects_catalog_url }}
  when:
    - eclipse_installer_redirectable_projects_catalog_url is defined
    - eclipse_installer_redirectable_projects_catalog_url

- name: Add support for SWT scaling for high dpi display support to config.ini file
  lineinfile:
    dest: '{{ eclipse_installer_folder }}/configuration/config.ini'
    regexp: ^swt\.autoScale
    line: swt.autoScale=exact

- name: Configure Eclipse Installer user preferences
  copy:
    src: user_home/
    dest: '~'

- name: Create ~/.local/share/applications directory if it does not exist
  file:
    path: ~/.local/share/applications
    state: directory
    mode: 0755

- name: Create Eclipse Installer launcher shortcut
  template:
    src: '{{ item }}.j2'
    dest: ~/.local/share/applications/{{ item }}
  with_items:
    - eclipse-installer.desktop
