---

- name: Installing libwebkitgtk for eclipse browser support
  become: true
  apt:
    name: libwebkitgtk-1.0-0
    state: latest
    purge: true
    autoremove: true

- name: Creating {{ eclipse_installer_folder | dirname }} directory if it does not exist
  file:
    path: '{{ eclipse_installer_folder | dirname }}'
    state: directory
    mode: 0755

- name: Downloading Eclipse Installer binaries
  get_url:
    url: '{{ eclipse_installer_download_url }}'
    dest: '{{ eclipse_installer_folder | dirname }}'
    timeout: 60
  register: archive

- name: Remove previous {{ eclipse_installer_folder }} direcory
  file:
    path: '{{ eclipse_installer_folder }}'
    state: absent

- name: Extract Eclipse Installer binaries
  unarchive:
    src: '{{ archive.dest }}'
    dest: '{{ eclipse_installer_folder | dirname }}'

- name: Remove downloaded Eclipse Installer archive
  file:
    path: '{{ archive.dest }}'
    state: absent

- name: Configure Eclipse Installer configuration
  copy:
    src: eclipse/
    dest: '{{ eclipse_installer_folder }}'

- name: Add location eclipse installer projects to config.ini file
  lineinfile:
    dest: '{{ eclipse_installer_folder }}/configuration/config.ini'
    regexp: ^oomph\.redirection\.local\.ide
    line: oomph.redirection.local.ide=index:/redirectable.projects.setup->file:{{ ansible_env.HOME | expanduser }}/.eclipse/org.eclipse.oomph.setup/setups/local.ide.setup

- name: Add support for SWT scaling for high dpi display support to config.ini file
  lineinfile:
    dest: '{{ eclipse_installer_folder }}/configuration/config.ini'
    regexp: ^swt\.autoScale
    line: swt.autoScale=exact

- name: Configure Eclipse Installer user preferences
  copy:
    src: user_home/
    dest: '~'

- name: Initialize an empty list for storing paths to Eclipse Installer setup projects
  set_fact:
    project_setup_files: []

- name: Cloning all configured Eclipse installer projects
  include_tasks: installer-projects.yml
  with_items: '{{ eclipse_installer_projects }}'
  loop_control:
    loop_var: git_url

- name: Create Eclipse installer local project catalog
  template:
    src: '{{ item }}.j2'
    dest: ~/.eclipse/org.eclipse.oomph.setup/setups/{{ item }}
  with_items:
    - local.ide.setup

- name: Create ~/.local/share/applications directory if it does not exist
  file:
    path: ~/.local/share/applications
    state: directory
    mode: 0755

- name: Create Eclipse Installer launcher shortcut
  template:
    src: '{{ item }}.j2'
    dest: ~/.local/share/applications/{{ item }}
  with_items:
    - eclipse-installer.desktop
