---
- import_tasks: packages.yml

- name: Configure look and feel settings of the user environment
  copy: 
    src: user_home/
    dest: '~'

- name: Configure OS environment
  become: true
  copy:
    src: etc/
    dest: /etc

- name: Remove 127.0.1.1 entry from hosts file
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: ^127\.0\.1\.1
    state: absent
