---
- import_tasks: packages.yml

- name: Configure look and feel settings of the user environment
  copy: 
    src: user_home/
    dest: '~'

- name: Configure look and feel templated settings of the user environment
  template:
    src: '{{ item.src }}'
    dest: '~/{{ item.path }}'
  with_filetree: templates/user_home/
  when: item.state == 'file'

- name: Configure OS environment
  become: true
  copy:
    src: etc/
    dest: /etc

- name: Remove 127.0.1.1 entry from hosts file
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: ^127\.0\.1\.1
    state: absent
