# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE = File.basename(File.dirname(__FILE__))

load '../vagrantfile-parent.rb'

Vagrant.configure('2') do |config|
    config.vm.provision 'environment', type:'ansible_local' do |ansible|
        ansible.playbook = 'environment.yml'
        ansible.extra_vars = CONFIG
    end
end
