alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls -F --color=auto --show-control-chars'
alias l='ls -C'
alias la='ls -Al'
alias ll='ls -al'
