---
- name: Create {{ maven_install_folder | dirname }} directory if it does not exist
  file:
    path: '{{ maven_install_folder | dirname }}'
    state: directory
    mode: 0755

- name: Download Apache Maven binaries
  get_url:
    url: '{{ maven_download_url }}'
    dest: '{{ maven_install_folder | dirname }}'
    checksum: '{{ maven_download_checksum }}'
    validate_certs: false
    timeout: 60
  register: archive

- name: Extract Apache Maven binaries
  unarchive:
    src: '{{ archive.dest }}'
    dest: '{{ maven_install_folder | dirname }}'

- name: Remove downloaded Apache Maven archive
  file:
    path: '{{ archive.dest }}'
    state: absent

- name: Remove previous apache-maven direcory
  file:
    path: '{{ maven_install_folder }}'
    state: absent

- name: Move the recently installed version of Apache Maven to apache-maven
  shell: mv -f {{ maven_install_folder | dirname }}/apache-maven-* {{ maven_install_folder }}

- name: Register M2_HOME environment variable
  lineinfile:
    dest: ~/.profile
    regexp: 'M2_HOME='
    line: 'M2_HOME="{{ maven_install_folder | expanduser }}"'

- name: Register PATH envioronment variable
  lineinfile:
    dest: ~/.profile
    regexp: 'PATH="\$M2_HOME'
    line: 'PATH="$M2_HOME/bin:$PATH"'

- name: Download and install maven bash completions from {{ maven_bash_completion_download_url }}
  become: true
  get_url:
    url: '{{ maven_bash_completion_download_url }}'
    dest: /etc/bash_completion.d/mvn
    mode: 0644
