---
- name: Register Atlassian repository public key
  become: true
  apt_key:
    url: https://packages.atlassian.com/api/gpg/key/public
    keyring: /etc/apt/trusted.gpg.d/atlassian.gpg
    state: present

- name: Configure apt sources list for Atlassian repository
  become: true
  apt_repository:
    repo: deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib
    filename: atlassian
    state: present

- name: Install Atlassian SDK
  become: true
  apt:
    name: atlassian-plugin-sdk
    state: latest
