---
- name: Create {{ jdk_install_folder | dirname }} directory if it does not exist
  file:
    path: '{{ jdk_install_folder | dirname }}'
    state: directory
    mode: 0755

- name: Download Oracle Java Development Kit 8 binaries
  get_url:
    url: '{{ jdk_download_url }}'
    dest: '{{ jdk_install_folder | dirname }}'
    headers:
      Cookie: oraclelicense=accept-securebackup-cookie
    checksum: '{{ jdk_download_checksum }}'
    validate_certs: false
    timeout: 60
  register: archive

- name: Extract Oracle Java Development Kit 8 binaries
  unarchive:
    src: '{{ archive.dest }}'
    dest: '{{ jdk_install_folder | dirname }}'

- name: Remove downloaded Oracle Java Development Kit 8 archive
  file:
    path: '{{ archive.dest }}'
    state: absent

- name: Remove previous Oracle Java Development Kit 8 direcory
  file:
    path: '{{ jdk_install_folder }}'
    state: absent

- name: Move Oracle Java Development Kit 8 folder to oracle-jdk8
  shell: mv -f {{ jdk_install_folder | dirname }}/jdk1.8.* {{ jdk_install_folder }}

- name: Configure environment variables
  template:
    src: '{{ item.src }}'
    dest: '~/{{ item.path }}'
  with_filetree: templates/user_home/
  when: item.state == 'file'
