# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE = File.basename(File.dirname(__FILE__))

load '../../scripts/vagrantfile-parent.rb'

Vagrant.configure('2') do |config|
    config.run_ansible('environment', 'environment.yaml', CONFIG)
end
