# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE = File.basename(File.dirname(__FILE__))

load '../../scripts/vagrantfile-parent.rb'

Vagrant.configure('2') do |config|
    config.vm.provision 'environment', type:'ansible_local' do |ansible|
        ansible.compatibility_mode = '2.0'
        ansible.playbook = 'environment.yml'
        ansible.extra_vars = CONFIG
    end

    config.vm.provider 'virtualbox' do |box|
        box.memory = 4608
    end

end
