---
- name: Registering google-chrome PGP key
  become: true
  apt_key:
    file: '{{ role_path }}/files/linux_signing_key.pub'
    keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg
    state: present

- name: Configure apt sources list for google-chrome
  become: true
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present

- name: Install google-chrome
  become: true
  apt:
    name: google-chrome-stable
    state: latest

- name: Configure initial google-chrome settings
  copy:
    src: user_home/
    dest: '~'

- name: Add google-chrome shortcut to the pannel
  replace:
    path: ~/.config/lxpanel/LXDE/panels/panel
    regexp: ([^\S\n]+Button {[^}]+})
    replace: |-
        \1
        Button {
          id=google-chrome.desktop
        }
