---
- name: Install git packages
  become: true
  apt:
    name: git-gui
    state: latest

- name: Configure menu items and integrations
  copy:
    src: user_home/
    dest: '~'

- name: Create .gitconfig
  template:
    src: .gitconfig.j2
    dest: ~/.gitconfig

- name: Set correct permissions on id_rsa
  file:
    path: ~/.ssh/id_rsa
    state: touch
    mode: 0600
