# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE = File.basename(File.dirname(__FILE__))

load '../../scripts/vagrantfile-parent.rb'

Vagrant.configure('2') do |config|
    config.vm.network "forwarded_port", guest: 80, host: 1080
    config.vm.network "forwarded_port", guest: 4502, host: 4502
    config.vm.network "forwarded_port", guest: 4503, host: 4503
    config.run_ansible('environment', 'environment.yaml', CONFIG)
end
