---

- name: Copy user configurations for proxy
  copy:
    src: user_home/
    dest: '~'

- name: Set correct permissions on ssh config
  file:
    path: ~/.ssh/config
    state: touch
    mode: 0660
